# Copyright (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_call:

jobs:
  check-changes:
    name: "Checking for changes"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      fast-mapping-changed: ${{ steps.filter.outputs.fast-mapping-location }}
      its-planner-changed: ${{ steps.filter.outputs.its-planner-location }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: false
      - name: Configure paths to look for changes
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        with:
          filters: |
            fast-mapping-location:
              - 'robotics-ai-suite/components/fast-mapping/**'
            its-planner-location:
              - 'robotics-ai-suite/components/its-planner/**'

  debug:
    name: "Just a debug message"
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
      - name: Print changed components
        run: |
          echo "Fast Mapping changed: ${{ needs.check-changes.outputs.fast-mapping-changed }}"
          echo "ITS Planner changed: ${{ needs.check-changes.outputs.its-planner-changed }}"
          echo "${{ needs.check-changes.outputs }}" | jq .
